---
permalink: protect/task_configure_storage_replication_adapter_for_san_environment.html 
sidebar: sidebar 
keywords:  
summary: 您必須先設定儲存系統、再執行Site Recovery Manager（SRM）的儲存複寫介面卡（SRA）。 
---
= 設定 SAN 環境的儲存複寫介面卡
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先設定儲存系統、再執行Site Recovery Manager（SRM）的儲存複寫介面卡（SRA）。

*您需要的是什麼*

您必須在受保護的站台和恢復站台上安裝下列程式：

* SRM
+
有關安裝SRM的說明文件、請參閱VMware網站。

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager文件"]

* SRA
+
介面卡安裝在SRM上。



*步驟*

. 確認主ESXi主機已連線至受保護站台上主要儲存系統的LUN。
. 確認 LUN 位於具有的 igroup 中 `ostype` 選項在主儲存系統上設為 _VMware_ 。
. 確認恢復站台的ESXi主機與儲存虛擬機器（SVM）之間具有適當的FC或iSCSI連線。
+
您可以透過驗證 ESXi 主機是否已在 SVM 上連接本機 LUN 、或使用來執行此動作 `fcp show initiators` 命令或 `iscsi show initiators` SVM 上的命令。





== 設定NAS環境的儲存複寫介面卡

*您需要的是什麼*

您必須在受保護的站台和恢復站台上安裝下列程式：

* SRM
+
如需安裝SRM的相關文件、請參閱VMware網站。

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager文件"]

* SRA
+
介面卡安裝在SRM和SRA伺服器上。



*步驟*

. 確認受保護站台的資料存放區包含已向vCenter Server註冊的虛擬機器。
. 確認受保護站台的ESXi主機已從儲存虛擬機器（SVM）掛載NFS匯出磁碟區。
. 使用Array Manager精靈將陣列新增至SRM時、請確認「* NFS Addresses *（* NFS位址*）」欄位中已指定有效位址、例如有NFS匯出的IP位址、主機名稱或FQDN。
. 使用 `ping` 在恢復站台上的每個 ESXi 主機上執行命令、以驗證主機是否有 VMkernel 連接埠、可存取用於從 SVM 匯出 NFS 的 IP 位址。


https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]
